# Generated by Django 6.0.1 on 2026-01-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Kripto Sembolü')),
                ('price', models.FloatField(verbose_name='Güncel Fiyat')),
                ('volume', models.FloatField(default=0, verbose_name='24 Saatlik Hacim')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Piyasa Verisi',
                'verbose_name_plural': 'Piyasa Verileri',
            },
        ),
    ]
